application: www-todoapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"

inbound_services:
- warmup

handlers:

- url: /_ah/spi/.*
  script: run.api

- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /static
  static_dir: todo_app/static

- url: .*
  script: run.app